# Generated by Django 5.2.7 on 2025-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="testVariable",
            field=models.TextField(
                blank=True,
                default="HALLO",
                help_text="Nutzlose Variable um migrations zu testen",
            ),
        ),
    ]
