# Generated by Django 5.2.4 on 2025-08-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfiguration',
            name='conflict_check_calendars',
            field=models.JSONField(default=list, help_text='List of calendar IDs to check for scheduling conflicts'),
        ),
    ]
