# Generated by Django 5.2.5 on 2025-08-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaleadform',
            name='is_active',
        ),
    ]
