# Generated by Django 5.2.6 on 2025-09-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='current_plan',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='subscription_status',
            field=models.CharField(choices=[('none', 'None'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], default='none', help_text='Current subscription status (mirrors Stripe status)', max_length=20),
        ),
    ]
