# Generated by Django 5.2.4 on 2025-07-30 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the call task', max_length=20)),
                ('retries', models.IntegerField(default=0, help_text='Number of retry attempts made')),
                ('read', models.BooleanField(default=False, help_text='Whether the task has been read/acknowledged')),
                ('usp', models.TextField(blank=True, help_text='Unique Selling Proposition for this call')),
                ('bscript', models.TextField(blank=True, help_text='Call script or talking points for the agent')),
                ('next_call', models.DateTimeField(blank=True, help_text='Scheduled time for the next call attempt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent assigned to handle this call task', on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='core.agent')),
                ('lead', models.ForeignKey(blank=True, help_text='Lead associated with this call task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_call'], name='core_callta_status_b92001_idx'), models.Index(fields=['agent', 'status'], name='core_callta_agent_i_6570d9_idx'), models.Index(fields=['next_call'], name='core_callta_next_ca_d8b39f_idx')],
            },
        ),
    ]
