# Generated by Django 5.2.4 on 2025-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='call_from',
            field=models.TimeField(default='09:00:00', help_text='Start time for calls'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='call_to',
            field=models.TimeField(default='17:00:00', help_text='End time for calls'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='character',
            field=models.TextField(blank=True, default='I am a helpful and professional AI assistant.', help_text='Agent character/personality description'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='greeting_inbound',
            field=models.TextField(blank=True, default='Hello! How can I help you today?', help_text='Greeting for inbound calls'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='greeting_outbound',
            field=models.TextField(blank=True, default="Hello! I'm calling from our team. Is this a good time to talk?", help_text='Greeting for outbound calls'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='language',
            field=models.CharField(default='en', help_text='Agent language', max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='workdays',
            field=models.JSONField(blank=True, default=list, help_text="List of working days, e.g., ['monday', 'tuesday', 'wednesday']"),
        ),
    ]
