# Generated by Django 5.2.4 on 2025-07-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(
                blank=True,
                help_text='Workspace this lead belongs to',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='leads',
                to='core.workspace'
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='integration_provider',
            field=models.CharField(
                blank=True,
                choices=[('meta', 'Meta'), ('google', 'Google'), ('manual', 'Manual')],
                help_text='Integration provider source',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='variables',
            field=models.JSONField(
                default=dict,
                help_text='Concrete lead variables from integration'
            ),
        ),
    ]
