# Generated by Django 5.2.4 on 2025-07-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Customer ID for billing",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="name",
            field=models.CharField(
                default="", help_text="Display name for the calendar", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google Calendar"),
                    ("outlook", "Microsoft Outlook"),
                ],
                default="google",
                max_length=20,
            ),
        ),
    ]
