# Generated by Django 5.2.5 on 2025-09-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadfunnel",
            name="custom_variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Variables extracted from connected form questions (Meta API response)",
            ),
        ),
    ]
