# Generated by Django 5.2.4 on 2025-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cosmetic_features',
            field=models.JSONField(blank=True, default=dict, help_text='Non-measurable plan features like whitelabel, priority support, etc.'),
        ),
    ]
