# Generated by Django 5.2.5 on 2025-09-05 14:19

from django.db import migrations


def coerce_to_list(apps, schema_editor):
    """Convert custom_variables from dict to list format"""
    LeadFunnel = apps.get_model('core', 'LeadFunnel')
    
    for funnel in LeadFunnel.objects.all():
        val = funnel.custom_variables
        
        if isinstance(val, dict):
            # If it has a 'variables' key with a list, use that list
            if 'variables' in val and isinstance(val['variables'], list):
                funnel.custom_variables = val['variables']
            else:
                # Otherwise convert dict keys to list
                funnel.custom_variables = list(val.keys())
            
            funnel.save(update_fields=['custom_variables'])


def reverse_coerce(apps, schema_editor):
    """Reverse migration: convert list back to dict format"""
    LeadFunnel = apps.get_model('core', 'LeadFunnel')
    
    for funnel in LeadFunnel.objects.all():
        val = funnel.custom_variables
        
        if isinstance(val, list):
            # Convert list back to dict format with 'variables' key
            funnel.custom_variables = {'variables': val}
            funnel.save(update_fields=['custom_variables'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(coerce_to_list, reverse_coerce),
    ]
