# Generated by Django 5.2.4 on 2025-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='prompt',
            field=models.TextField(blank=True, help_text='Agent prompt/instructions for AI behavior'),
        ),
    ]
