# Generated by Django 4.2.17 on 2025-08-26 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutlookSubAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "act_as_upn",
                    models.EmailField(
                        help_text="Target mailbox (UPN/email)", max_length=254
                    ),
                ),
                (
                    "mailbox_object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AAD user object id if known",
                        max_length=128,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("self", "Self / same user"),
                            ("shared", "Shared mailbox/calendar"),
                            ("delegate", "Delegated access"),
                            ("app_only", "Application-permission impersonation"),
                            ("resource", "Room/equipment"),
                        ],
                        default="self",
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outlook_calendar",
                    models.ForeignKey(
                        help_text="The main Outlook account that owns the OAuth tokens",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_accounts",
                        to="core.outlookcalendar",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["act_as_upn"], name="core_outloo_act_as__57a883_idx"
                    ),
                    models.Index(
                        fields=["outlook_calendar", "active"],
                        name="core_outloo_outlook_bb94b9_idx",
                    ),
                ],
                "unique_together": {("outlook_calendar", "act_as_upn")},
            },
        ),
        migrations.CreateModel(
            name="GoogleSubAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "act_as_email",
                    models.EmailField(
                        help_text="Target user/resource email you operate on behalf of",
                        max_length=254,
                    ),
                ),
                (
                    "act_as_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google user id if known",
                        max_length=128,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("self", "Self / same user"),
                            ("shared", "Shared calendar"),
                            ("delegate", "Delegated access"),
                            (
                                "domain_impersonation",
                                "Domain-wide delegation (service account)",
                            ),
                            ("resource", "Resource calendar"),
                        ],
                        default="self",
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "google_calendar",
                    models.ForeignKey(
                        help_text="The main Google account that owns the OAuth tokens",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_accounts",
                        to="core.googlecalendar",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["act_as_email"], name="core_google_act_as__f93d4a_idx"
                    ),
                    models.Index(
                        fields=["google_calendar", "active"],
                        name="core_google_google__32af1c_idx",
                    ),
                ],
                "unique_together": {("google_calendar", "act_as_email")},
            },
        ),
    ]
