# Generated by Django 5.2.4 on 2025-07-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calltask",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("call_triggered", "call_triggered"),
                    ("in_progress", "in_progress"),
                    ("retry", "retry"),
                    ("waiting", "waiting"),
                ],
                default="scheduled",
                help_text="Current status of the call task",
                max_length=20,
            ),
        ),
    ]
