# Generated by Django 5.2.4 on 2025-08-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_conflict_check_calendars'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfiguration',
            name='meeting_address',
            field=models.TextField(blank=True, help_text='Meeting address for in-person meetings (optional)', null=True),
        ),
        migrations.AddField(
            model_name='calendarconfiguration',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Meeting link for online meetings (optional)', null=True),
        ),
        migrations.AddField(
            model_name='calendarconfiguration',
            name='meeting_type',
            field=models.CharField(choices=[('online', 'Online Meeting'), ('in_person', 'In Person'), ('phone', 'Phone Call')], default='online', help_text='Type of meeting', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarconfiguration',
            name='name',
            field=models.CharField(default=0, help_text='Name/title for this calendar configuration', max_length=255),
            preserve_default=False,
        ),
    ]
