# Generated by Django 5.2.4 on 2025-07-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_agent_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_sample',
            field=models.FileField(blank=True, help_text='Voice sample file (.wav format)', null=True, upload_to='voice_samples/'),
        ),
    ]
