# Generated by Django 5.2.5 on 2025-08-12 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_metaleadform_is_active_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadProcessingStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, help_text='Date of the statistics')),
                ('total_received', models.IntegerField(default=0, help_text='Total leads received from webhooks')),
                ('processed_with_agent', models.IntegerField(default=0, help_text='Leads processed with active agent')),
                ('ignored_no_funnel', models.IntegerField(default=0, help_text='Leads ignored - no funnel configured')),
                ('ignored_no_agent', models.IntegerField(default=0, help_text='Leads ignored - no agent assigned')),
                ('ignored_inactive_agent', models.IntegerField(default=0, help_text='Leads ignored - agent inactive')),
                ('ignored_inactive_funnel', models.IntegerField(default=0, help_text='Leads ignored - funnel inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_processing_stats', to='core.workspace')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['workspace', 'date'], name='core_leadpr_workspa_eefb3c_idx'), models.Index(fields=['date'], name='core_leadpr_date_7886a3_idx')],
                'unique_together': {('workspace', 'date')},
            },
        ),
    ]
