# Generated by Django 5.2.4 on 2025-07-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Unit of measurement for this feature (e.g., 'calls', 'agents', 'minutes')",
                max_length=50,
                null=True,
            ),
        ),
    ]
