# Generated by Django 5.2.5 on 2025-09-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_leadfunnel_custom_variables"),
    ]

    operations = []
