# Generated by Django 5.2.7 on 2025-10-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_agent_testvariable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="testVariable",
        ),
    ]
