# Generated by Django 5.2.4 on 2025-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calltask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltask',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the call task', max_length=20),
        ),
    ]
