# Generated by Django 5.2.7 on 2025-10-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_agent_testvariable"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="random_value",
            field=models.CharField(default="3"),
        ),
    ]
