# Generated by Django 5.2.4 on 2025-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livekit_agent_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='livekitagent',
            new_name='core_liveki_token_64f5d1_idx',
            old_name='core_liveki_token_b4a5d5_idx',
        ),
        migrations.RenameIndex(
            model_name='livekitagent',
            new_name='core_liveki_name_167fd8_idx',
            old_name='core_liveki_name_3f1e82_idx',
        ),
        migrations.RenameIndex(
            model_name='livekitagent',
            new_name='core_liveki_expires_383b65_idx',
            old_name='core_liveki_expires_9b2c41_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='integration_provider',
            field=models.CharField(blank=True, choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google'), ('manual', 'Manual Entry')], help_text='Integration provider source', max_length=20, null=True),
        ),
    ]
