# Generated by Django 5.2.4 on 2025-07-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_calltask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text='Whether this workspace has used their trial period'),
        ),
    ]
