# Generated by Django 5.2.5 on 2025-09-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_merge_20250908_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="transcript",
            field=models.JSONField(
                blank=True,
                help_text="Complete conversation transcript as JSON array of messages",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="integration_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meta", "Meta (Facebook/Instagram)"),
                    ("google", "Google"),
                    ("manual", "Manual Entry"),
                    ("custom-webhook", "Custom Webhook"),
                    ("csv", "CSV File"),
                ],
                help_text="Integration provider source",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leadfunnel",
            name="custom_variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of variable keys discovered from connected form questions (Meta API)",
            ),
        ),
    ]
