# Generated by Django 5.2.5 on 2025-08-12 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='integration_provider',
            field=models.CharField(blank=True, choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google'), ('manual', 'Manual Entry'), ('custom-webhook', 'Custom Webhook')], help_text='Integration provider source', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='WebhookLeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for this webhook source', max_length=255)),
                ('public_key', models.CharField(db_index=True, help_text='Public identifier used in the inbound webhook URL', max_length=64, unique=True)),
                ('token', models.CharField(help_text='Bearer token required in Authorization header', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_funnel', models.OneToOneField(help_text='Lead funnel connected to this webhook source', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_source', to='core.leadfunnel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_lead_sources', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_key'], name='core_webhoo_public__941b75_idx')],
            },
        ),
    ]
