# Generated by Django 5.2.4 on 2025-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_voice_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_picture',
            field=models.ImageField(blank=True, help_text='Voice picture file (.png or .jpg format)', null=True, upload_to='voice_pictures/'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_sample',
            field=models.FileField(blank=True, help_text='Voice sample file (.wav or .mp3 format)', null=True, upload_to='voice_samples/'),
        ),
    ]
