# Generated by Django 5.2.4 on 2025-07-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_unit_to_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="endpoints",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of API endpoints related to this feature",
            ),
        ),
    ]
