# Generated by Django 5.2.4 on 2025-08-02 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_calendar_configuration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarMCPAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique MCP agent name for Google Calendar authentication', max_length=255, unique=True)),
                ('token', models.CharField(help_text='Random string token for MCP authentication', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration date (1 year from creation)')),
            ],
            options={
                'db_table': 'core_google_calendar_mcp_agent',
                'indexes': [models.Index(fields=['token'], name='core_google_token_9c4c4f_idx'), models.Index(fields=['name'], name='core_google_name_de0566_idx'), models.Index(fields=['expires_at'], name='core_google_expires_d93055_idx')],
            },
        ),
    ]
