# Generated by Django 5.2.5 on 2025-08-13 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lead_integration_provider_webhookleadsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_email', models.EmailField(help_text='Primary UPN/email of the Microsoft account', max_length=254)),
                ('tenant_id', models.CharField(help_text='Azure AD Tenant ID (tid)', max_length=128)),
                ('ms_user_id', models.CharField(help_text='Microsoft user object ID (oid)', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('timezone_windows', models.CharField(blank=True, default='', help_text="Windows time zone id (e.g., 'W. Europe Standard Time')", max_length=100)),
                ('refresh_token', models.TextField(editable=False, help_text='OAuth refresh token (encrypted at rest)')),
                ('access_token', models.TextField(editable=False, help_text='OAuth access token (encrypted at rest)')),
                ('token_expires_at', models.DateTimeField(help_text='When access token expires')),
                ('scopes_granted', models.JSONField(default=list, help_text='Granted OAuth scopes')),
                ('active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_errors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_calendar_connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_calendar_connections', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='MicrosoftCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='Microsoft Calendar ID', max_length=255, unique=True)),
                ('primary', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True, help_text='Whether current user can edit this calendar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_calendar', to='core.calendar')),
                ('connection', models.ForeignKey(blank=True, help_text='OAuth connection that provides access to this calendar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='core.microsoftcalendarconnection')),
            ],
        ),
        migrations.CreateModel(
            name='MicrosoftSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_id', models.CharField(max_length=255, unique=True)),
                ('resource', models.CharField(default='me/events', max_length=255)),
                ('client_state', models.CharField(blank=True, default='', max_length=255)),
                ('expiration_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.microsoftcalendarconnection')),
            ],
        ),
        migrations.AddIndex(
            model_name='microsoftcalendarconnection',
            index=models.Index(fields=['workspace', 'active'], name='core_micros_workspa_db53b2_idx'),
        ),
        migrations.AddIndex(
            model_name='microsoftcalendarconnection',
            index=models.Index(fields=['token_expires_at'], name='core_micros_token_e_843008_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='microsoftcalendarconnection',
            unique_together={('workspace', 'primary_email')},
        ),
        migrations.AddIndex(
            model_name='microsoftsubscription',
            index=models.Index(fields=['connection'], name='core_micros_connect_18b10e_idx'),
        ),
        migrations.AddIndex(
            model_name='microsoftsubscription',
            index=models.Index(fields=['expiration_at'], name='core_micros_expirat_70a406_idx'),
        ),
    ]
