# Generated by Django 5.2.4 on 2025-08-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_google_calendar_mcp_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendar',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='OAuth connection that provides access to this calendar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='core.googlecalendarconnection'),
        ),
        migrations.AlterField(
            model_name='googlecalendar',
            name='access_token',
            field=models.CharField(blank=True, default='', editable=False, help_text='DEPRECATED: Use connection.access_token', max_length=255),
        ),
        migrations.AlterField(
            model_name='googlecalendar',
            name='refresh_token',
            field=models.CharField(blank=True, default='', editable=False, help_text='DEPRECATED: Use connection.refresh_token', max_length=255),
        ),
        migrations.AlterField(
            model_name='googlecalendar',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use connection.scopes'),
        ),
        migrations.AlterField(
            model_name='googlecalendar',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: Use connection.token_expires_at', null=True),
        ),
    ]
