# Generated by Django 5.2.4 on 2025-07-31 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_liveki_token_b4a5d5_idx_core_liveki_token_64f5d1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('in_progress', 'in_progress'), ('retry', 'retry'), ('waiting', 'waiting')], default='scheduled', help_text='Current status of the call task', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Number of retry attempts made')),
                ('phone', models.CharField(help_text='Phone number to call', max_length=20)),
                ('next_call', models.DateTimeField(help_text='Scheduled time for the next call attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent assigned to handle this call task', on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='core.agent')),
                ('lead', models.OneToOneField(blank=True, help_text='Lead associated with this call task (null for test calls)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_task', to='core.lead')),
                ('workspace', models.ForeignKey(help_text='Workspace associated with this call task', on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_call'], name='core_callta_status_b92001_idx'), models.Index(fields=['agent', 'status'], name='core_callta_agent_i_6570d9_idx'), models.Index(fields=['next_call'], name='core_callta_next_ca_d8b39f_idx')],
            },
        ),
    ]
