# Generated by Django 5.2.4 on 2025-08-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_lead_integration_provider_webhookleadsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltask",
            name="retry_reasons",
            field=models.JSONField(
                default=list,
                help_text="Append-only list of retry reason dicts: {reason, hint, at}",
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="disconnection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_hangup", "User Hangup"),
                    ("agent_hangup", "Agent Hangup"),
                    ("call_transfer", "Call Transfer"),
                    ("voicemail_reached", "Voicemail Reached"),
                    ("inactivity", "Inactivity Timeout"),
                    ("max_duration_reached", "Maximum Duration Reached"),
                    ("dial_busy", "Dial Busy"),
                    ("dial_failed", "Dial Failed"),
                    ("dial_no_answer", "No Answer"),
                    ("invalid_destination", "Invalid Destination"),
                    (
                        "telephony_provider_permission_denied",
                        "Telephony Provider Permission Denied",
                    ),
                    (
                        "telephony_provider_unavailable",
                        "Telephony Provider Unavailable",
                    ),
                    ("sip_routing_error", "SIP Routing Error"),
                    ("marked_as_spam", "Marked as Spam"),
                    ("user_declined", "User Declined"),
                    ("concurrency_limit_reached", "Concurrency Limit Reached"),
                    ("no_valid_payment", "No Valid Payment"),
                    ("scam_detected", "Scam Detected"),
                    ("error_llm_websocket_open", "LLM Websocket Open Error"),
                    (
                        "error_llm_websocket_lost_connection",
                        "LLM Websocket Lost Connection",
                    ),
                    ("error_llm_websocket_runtime", "LLM Websocket Runtime Error"),
                    (
                        "error_llm_websocket_corrupt_payload",
                        "LLM Websocket Corrupt Payload",
                    ),
                    ("error_no_audio_received", "No Audio Received"),
                    ("error_asr", "ASR Error"),
                    ("error_hotcalls", "HotCalls Error"),
                    ("error_unknown", "Unknown Error"),
                    ("error_user_not_joined", "User Not Joined"),
                    ("registered_call_timeout", "Registered Call Timeout"),
                    ("preflight_call_log_failed", "Preflight Call Log Failed"),
                ],
                help_text="Reason for call disconnection",
                max_length=50,
                null=True,
            ),
        ),
    ]
