# Generated by Django 5.2.5 on 2025-09-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_transcript_to_calllog"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated summary of the call transcript",
                null=True,
            ),
        ),
    ]
