# Generated by Django 5.2.4 on 2025-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_extend_page_picture_url_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaleadform",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this lead form should process incoming leads",
            ),
        ),
    ]
