# Generated by Django 5.2.4 on 2025-07-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_voice_voice_picture_alter_voice_voice_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(default='123e4567-e89b-12d3-a456-426614174000', help_text='Workspace this lead belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mapping_workspace_leads', to='core.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('workspace', 'phone')},
        ),
    ]
