# Generated by Django 5.2.4 on 2025-07-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_workspace_to_leads'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of retry attempts for calls'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='workspace',
        ),
    ]
