# Generated by Django 5.2.5 on 2025-08-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calltask_retry_reasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltask',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Lead associated with this call task (null for test calls)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='core.lead'),
        ),
    ]
