# Generated by Django 5.2.4 on 2025-07-30 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_update_feature_unit_to_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.plan"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription that was active for this usage period",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.workspacesubscription",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "used_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.feature"
                    ),
                ),
                (
                    "usage_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usages",
                        to="core.workspaceusage",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="workspacesubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("workspace",),
                name="unique_active_subscription_per_workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspaceusage",
            unique_together={("workspace", "period_start", "period_end")},
        ),
        migrations.AlterUniqueTogether(
            name="featureusage",
            unique_together={("usage_record", "feature")},
        ),
    ]
