# Generated by Django 5.2.4 on 2025-07-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_agent_max_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='stripe_customer_id',
            field=models.CharField(
                blank=True, 
                help_text='Stripe Customer ID for billing', 
                max_length=255, 
                null=True, 
                unique=True
            ),
        ),
    ]
