# Generated by Django 5.2.4 on 2025-07-30 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_workspace_subscription_usage_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="endpoints",
        ),
        migrations.CreateModel(
            name="EndpointFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "route_name",
                    models.CharField(
                        db_index=True,
                        help_text="Django route name or regex pattern for the endpoint",
                        max_length=200,
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP method (GET, POST, etc.) - optional for broader matching",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="Feature that governs this endpoint",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoint_features",
                        to="core.feature",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["route_name"], name="core_endpoi_route_n_dc682a_idx"
                    ),
                    models.Index(
                        fields=["route_name", "http_method"],
                        name="core_endpoi_route_n_81ab13_idx",
                    ),
                ],
                "unique_together": {("route_name", "http_method")},
            },
        ),
    ]
