# Generated by Django 5.2.5 on 2025-08-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_calltask_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='max_call_duration_minutes',
            field=models.IntegerField(default=30, help_text='Maximum allowed call duration (minutes) before auto-cleanup of stuck IN_PROGRESS tasks'),
        ),
    ]
