# Generated by Django 5.2.4 on 2025-08-10 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_update_disconnection_reason_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="disconnection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_hangup", "User Hangup"),
                    ("agent_hangup", "Agent Hangup"),
                    ("call_transfer", "Call Transfer"),
                    ("voicemail_reached", "Voicemail Reached"),
                    ("inactivity", "Inactivity Timeout"),
                    ("max_duration_reached", "Maximum Duration Reached"),
                    ("dial_busy", "Dial Busy"),
                    ("dial_failed", "Dial Failed"),
                    ("dial_no_answer", "No Answer"),
                    ("invalid_destination", "Invalid Destination"),
                    (
                        "telephony_provider_permission_denied",
                        "Telephony Provider Permission Denied",
                    ),
                    (
                        "telephony_provider_unavailable",
                        "Telephony Provider Unavailable",
                    ),
                    ("sip_routing_error", "SIP Routing Error"),
                    ("marked_as_spam", "Marked as Spam"),
                    ("user_declined", "User Declined"),
                    ("concurrency_limit_reached", "Concurrency Limit Reached"),
                    ("no_valid_payment", "No Valid Payment"),
                    ("scam_detected", "Scam Detected"),
                    ("error_llm_websocket_open", "LLM Websocket Open Error"),
                    (
                        "error_llm_websocket_lost_connection",
                        "LLM Websocket Lost Connection",
                    ),
                    ("error_llm_websocket_runtime", "LLM Websocket Runtime Error"),
                    (
                        "error_llm_websocket_corrupt_payload",
                        "LLM Websocket Corrupt Payload",
                    ),
                    ("error_no_audio_received", "No Audio Received"),
                    ("error_asr", "ASR Error"),
                    ("error_hotcalls", "HotCalls Error"),
                    ("error_unknown", "Unknown Error"),
                    ("error_user_not_joined", "User Not Joined"),
                    ("registered_call_timeout", "Registered Call Timeout"),
                ],
                help_text="Reason for call disconnection",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the person being invited",
                        max_length=254,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Secure token for invitation acceptance (encrypted at rest)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the invitation",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this invitation expires (7 days from creation)"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted",
                        null=True,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace the user is being invited to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="core_worksp_token_126ea6_idx"),
                    models.Index(
                        fields=["email", "status"], name="core_worksp_email_538d7a_idx"
                    ),
                    models.Index(
                        fields=["workspace", "status"],
                        name="core_worksp_workspa_63175a_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_worksp_expires_5b24a3_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("workspace", "email"),
                        name="unique_pending_invitation_per_workspace_email",
                    )
                ],
                "unique_together": {("workspace", "email", "status")},
            },
        ),
    ]
