# Generated by Django 5.2.4 on 2025-07-31 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_has_used_trial_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='has_used_trial',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='subscription_status',
        ),
    ]
