# Generated by Django 5.2.5 on 2025-08-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workspace_admin_user_workspace_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='kb_doc_id',
            field=models.UUIDField(blank=True, help_text='Knowledge Base document ID', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='kb_doc_name',
            field=models.CharField(blank=True, help_text='Knowledge Base document display name', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='kb_doc_size',
            field=models.IntegerField(blank=True, help_text='Knowledge Base document size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='kb_doc_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the KB document was last updated', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='kb_doc_url',
            field=models.URLField(blank=True, help_text='Knowledge Base document URL (PDF)', max_length=1000, null=True),
        ),
    ]
