# Generated by Django 5.2.5 on 2025-08-19 07:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agent_kb_doc_id_agent_kb_doc_name_agent_kb_doc_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='kb_doc_id',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='kb_doc_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='kb_doc_size',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='kb_doc_updated_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='kb_doc_url',
        ),
        migrations.AddField(
            model_name='agent',
            name='kb_pdf',
            field=models.FileField(blank=True, help_text='Single Knowledge Base PDF for this agent', null=True, upload_to=core.models.agent_kb_upload_path),
        ),
    ]
