# Generated by Django 5.2.4 on 2025-07-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_stripe_to_workspace'),
    ]

    operations = [
        # Add Stripe fields to Plan model
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(
                blank=True, 
                help_text='Stripe Product ID (prod_xxx)', 
                max_length=255, 
                null=True, 
                unique=True
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_monthly',
            field=models.CharField(
                blank=True, 
                help_text='Stripe Price ID for monthly billing (price_xxx)', 
                max_length=255, 
                null=True
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_yearly',
            field=models.CharField(
                blank=True, 
                help_text='Stripe Price ID for yearly billing (price_xxx)', 
                max_length=255, 
                null=True
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_monthly',
            field=models.DecimalField(
                blank=True, 
                decimal_places=2, 
                help_text='Monthly price in EUR', 
                max_digits=10, 
                null=True
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_yearly',
            field=models.DecimalField(
                blank=True, 
                decimal_places=2, 
                help_text='Yearly price in EUR', 
                max_digits=10, 
                null=True
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(
                default=True, 
                help_text='Is this plan available for new subscriptions?'
            ),
        ),
        # Add subscription fields to Workspace model
        migrations.AddField(
            model_name='workspace',
            name='current_plan',
            field=models.ForeignKey(
                blank=True, 
                help_text='Current subscription plan', 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='workspaces', 
                to='core.plan'
            ),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription_status',
            field=models.CharField(
                choices=[
                    ('trial', 'Trial'), 
                    ('active', 'Active'), 
                    ('cancelled', 'Cancelled'), 
                    ('past_due', 'Past Due'), 
                    ('unpaid', 'Unpaid')
                ], 
                default='trial', 
                help_text='Current subscription status', 
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='workspace',
            name='stripe_subscription_id',
            field=models.CharField(
                blank=True, 
                help_text='Current Stripe Subscription ID (sub_xxx)', 
                max_length=255, 
                null=True
            ),
        ),
    ]
