# Generated by Django 5.2.4 on 2025-08-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_calllog_disconnection_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="phone_numbers",
        ),
        migrations.AddField(
            model_name="agent",
            name="phone_number",
            field=models.ForeignKey(
                blank=True,
                help_text="Phone number assigned to this agent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="core.phonenumber",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="current_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Current subscription plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspaces",
                to="core.plan",
            ),
        ),
    ]
