# Generated by Django 5.2.5 on 2025-08-15 23:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agent_max_call_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='config_id',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='status',
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_task_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID of originating CallTask (not a foreign key, may be dangling)'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='target_ref',
            field=models.CharField(blank=True, help_text='Canonical call target reference from CallTask', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_lead_calllogs', to='core.lead'),
        ),
    ]
