# Generated by Django 5.2.4 on 2025-07-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_replace_endpoints_with_endpointfeature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpointfeature",
            name="http_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("PATCH", "PATCH"),
                    ("DELETE", "DELETE"),
                    ("HEAD", "HEAD"),
                    ("OPTIONS", "OPTIONS"),
                ],
                help_text="HTTP method (GET, POST, etc.) - optional for broader matching",
                max_length=10,
                null=True,
            ),
        ),
    ]
