# Generated by Django 5.2.4 on 2025-08-11 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_fix_agent_phone_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIPTrunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        help_text="SIP provider name (e.g., 'Twilio', 'Sipgate')",
                        max_length=100,
                    ),
                ),
                (
                    "sip_username",
                    models.CharField(
                        help_text="SIP authentication username", max_length=255
                    ),
                ),
                (
                    "sip_password",
                    models.CharField(
                        help_text="SIP authentication password (encrypted at rest)",
                        max_length=255,
                    ),
                ),
                (
                    "sip_host",
                    models.CharField(
                        help_text="SIP server domain/IP address", max_length=255
                    ),
                ),
                (
                    "sip_port",
                    models.IntegerField(default=5060, help_text="SIP server port"),
                ),
                (
                    "jambonz_carrier_id",
                    models.CharField(
                        blank=True,
                        help_text="Jambonz carrier ID for this trunk",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "livekit_trunk_id",
                    models.CharField(
                        blank=True,
                        help_text="LiveKit trunk ID for this provider",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this SIP trunk is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="agent",
            name="phone_number",
            field=models.ForeignKey(
                blank=True,
                help_text="Phone number assigned to this agent (agent accesses SIP trunk via agent.phone_number.sip_trunk)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="core.phonenumber",
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this phone number is active"
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="phonenumber",
            field=models.CharField(
                help_text="Phone number in E.164 format", max_length=17, unique=True
            ),
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="sip_trunk",
            field=models.OneToOneField(
                blank=True,
                help_text="SIP trunk associated with this phone number",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_number",
                to="core.siptrunk",
            ),
        ),
    ]
