# Generated by Django 5.2.5 on 2025-08-19 08:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agent_kb_doc_id_remove_agent_kb_doc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email_default_body',
            field=models.TextField(blank=True, help_text='Default body when sending the document via email', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='email_default_subject',
            field=models.CharField(blank=True, help_text='Default subject when sending the document via email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='send_document',
            field=models.FileField(blank=True, help_text='Single PDF that the agent can send via email', null=True, upload_to=core.models.agent_send_document_upload_path),
        ),
        migrations.AddField(
            model_name='workspace',
            name='smtp_enabled',
            field=models.BooleanField(default=False, help_text='Enable outbound email via this workspace SMTP configuration'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='smtp_from_email',
            field=models.EmailField(blank=True, default='', help_text='Sender email address for outbound messages', max_length=254),
        ),
        migrations.AddField(
            model_name='workspace',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='SMTP hostname', max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True, default='', help_text='SMTP password (encrypted at rest)'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='SMTP port'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Use implicit SSL/TLS'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Use STARTTLS'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='smtp_username',
            field=models.CharField(blank=True, default='', help_text='SMTP username', max_length=255),
        ),
    ]
