# Generated by Django 5.2.4 on 2025-07-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_workspace_stripe_customer_id_alter_calendar_name_and_more"),
        ("core", "0008_add_stripe_to_plans"),
    ]

    operations = []
