# Generated by Django 5.2.5 on 2025-08-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agent_config_id_remove_calllog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='event_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Idempotency key for a single call attempt (one CallLog per event_id)', null=True, unique=True),
        ),
    ]
