# Generated by Django 5.2.4 on 2025-08-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_subscription_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='subscription_status',
            field=models.CharField(choices=[('none', 'None'), ('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], default='none', help_text='Current subscription status (mirrors Stripe status)', max_length=20),
        ),
    ]
