# Generated by Django 5.2.4 on 2025-07-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_http_method_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minute", "Minute"),
                    ("general_unit", "General Unit"),
                    ("access", "Access"),
                    ("request", "Request"),
                    ("gb", "Gigabyte"),
                ],
                help_text="Unit type for this feature",
                max_length=20,
                null=True,
            ),
        ),
    ]
