# Generated by Django 5.2.5 on 2025-08-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010b_create_workspaceusage_if_missing2'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceusage',
            name='extra_call_minutes',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Extra purchased call minutes credited to this billing period', max_digits=15),
        ),
    ]
