# Generated by Django 5.2.4 on 2025-08-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_siptrunk_alter_agent_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltask",
            name="target_ref",
            field=models.CharField(
                blank=True,
                help_text="Canonical call target reference (e.g., 'lead:<uuid>', 'test_user:<uuid>', 'raw_phone:+49123')",
                max_length=255,
                null=True,
            ),
        ),
    ]
