# Generated by Django 5.2.4 on 2025-07-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_request_gb_unit_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="current_plan",
        ),
        migrations.AlterField(
            model_name="agent",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                help_text="Voice configuration for this agent",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="core.voice",
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="appointment_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="Scheduled appointment datetime when status is 'appointment_scheduled'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="endpointfeature",
            name="http_method",
            field=models.CharField(
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("PATCH", "PATCH"),
                    ("DELETE", "DELETE"),
                    ("HEAD", "HEAD"),
                    ("OPTIONS", "OPTIONS"),
                    ("*", "Any Method"),
                ],
                default="*",
                help_text="HTTP method (GET, POST, etc.) or '*' for any method",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="featureusage",
            name="used_amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="googlecalendar",
            name="access_token",
            field=models.CharField(
                editable=False,
                help_text="Google Calendar API access token (encrypted at rest)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendar",
            name="refresh_token",
            field=models.CharField(
                editable=False,
                help_text="Google Calendar API refresh token (encrypted at rest)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendarconnection",
            name="access_token",
            field=models.TextField(
                editable=False, help_text="OAuth access token (encrypted at rest)"
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendarconnection",
            name="refresh_token",
            field=models.TextField(
                editable=False, help_text="OAuth refresh token (encrypted at rest)"
            ),
        ),
        migrations.AlterField(
            model_name="metaintegration",
            name="access_token",
            field=models.TextField(
                editable=False, help_text="Meta API access token (encrypted at rest)"
            ),
        ),
        migrations.AlterField(
            model_name="metaintegration",
            name="verification_token",
            field=models.CharField(
                editable=False,
                help_text="Webhook verification token for Meta (encrypted at rest)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="planfeature",
            name="limit",
            field=models.DecimalField(
                decimal_places=3, help_text="Feature limit for this plan", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Token for email verification (encrypted at rest)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Token for password reset (encrypted at rest)",
                max_length=100,
                null=True,
            ),
        ),
    ]
