# Generated by Django 5.2.4 on 2025-08-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_workspace_subscription_status'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_workspace DROP COLUMN IF EXISTS trial_started_at;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_workspace DROP COLUMN IF EXISTS trial_ended_at;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
