# Generated by Assistant to repair missing table
from django.db import migrations


CREATE_TABLE_SQL = r"""
-- Ensure core_workspacesubscription exists
CREATE TABLE IF NOT EXISTS core_workspacesubscription (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    plan_id uuid NOT NULL,
    started_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_workspacesubscription_workspace_id_fk'
    ) THEN
        ALTER TABLE core_workspacesubscription
        ADD CONSTRAINT core_workspacesubscription_workspace_id_fk
        FOREIGN KEY (workspace_id)
        REFERENCES core_workspace (id)
        DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_workspacesubscription_plan_id_fk'
    ) THEN
        ALTER TABLE core_workspacesubscription
        ADD CONSTRAINT core_workspacesubscription_plan_id_fk
        FOREIGN KEY (plan_id)
        REFERENCES core_plan (id)
        DEFERRABLE INITIALLY DEFERRED;
    END IF;
END
$$;

-- Now create core_workspaceusage
CREATE TABLE IF NOT EXISTS core_workspaceusage (
    id uuid PRIMARY KEY,
    workspace_id uuid NOT NULL,
    subscription_id uuid NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_workspaceusage_workspace_id_fk'
    ) THEN
        ALTER TABLE core_workspaceusage
        ADD CONSTRAINT core_workspaceusage_workspace_id_fk
        FOREIGN KEY (workspace_id)
        REFERENCES core_workspace (id)
        DEFERRABLE INITIALLY DEFERRED;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_workspaceusage_subscription_id_fk'
    ) THEN
        ALTER TABLE core_workspaceusage
        ADD CONSTRAINT core_workspaceusage_subscription_id_fk
        FOREIGN KEY (subscription_id)
        REFERENCES core_workspacesubscription (id)
        DEFERRABLE INITIALLY DEFERRED;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'core_workspaceusage_unique_period'
    ) THEN
        ALTER TABLE core_workspaceusage
        ADD CONSTRAINT core_workspaceusage_unique_period
        UNIQUE (workspace_id, period_start, period_end);
    END IF;
END
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agent_email_default_body_agent_email_default_subject_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_TABLE_SQL,
            reverse_sql="""
            -- Do not drop table on reverse to avoid data loss
            SELECT 1;
            """,
        ),
    ]


