# Generated by Django 5.2.4 on 2025-07-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_major_model_restructure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Customer ID for billing",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_customer_id__isnull", False)),
                fields=("stripe_customer_id",),
                name="unique_stripe_customer_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_subscription_id__isnull", False)),
                fields=("stripe_subscription_id",),
                name="unique_stripe_subscription_id",
            ),
        ),
    ]
