# Dynamic ConfigMap Template
# Usage: envsubst < configmap.yaml | kubectl apply -f -
# Set variables first: PROJECT_PREFIX, ENVIRONMENT

apiVersion: v1
kind: ConfigMap
metadata:
  name: ${PROJECT_PREFIX}-config
  namespace: ${PROJECT_PREFIX}-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: config
    environment: ${ENVIRONMENT}
data:
  # Django settings
  ENVIRONMENT: "${ENVIRONMENT}"
  DEBUG: "${DEBUG}"
  TIME_ZONE: "${TIME_ZONE}"
  
  # Database configuration (non-sensitive)
  DB_ENGINE: "django.db.backends.postgresql"
  DB_PORT: "5432"
  DB_SSLMODE: "${DB_SSLMODE}"
  
  # Redis configuration (non-sensitive)  
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Storage configuration
  AZURE_STATIC_CONTAINER: "static"
  AZURE_MEDIA_CONTAINER: "media"
  
  # Security settings
  SECURE_SSL_REDIRECT: "${SECURE_SSL_REDIRECT}"
  SESSION_COOKIE_SECURE: "${SESSION_COOKIE_SECURE}"
  CSRF_COOKIE_SECURE: "${CSRF_COOKIE_SECURE}"
  SECURE_BROWSER_XSS_FILTER: "${SECURE_BROWSER_XSS_FILTER}"
  SECURE_CONTENT_TYPE_NOSNIFF: "${SECURE_CONTENT_TYPE_NOSNIFF}"
  X_FRAME_OPTIONS: "${X_FRAME_OPTIONS}"
  
  # Celery settings
  CELERY_TASK_ALWAYS_EAGER: "${CELERY_TASK_ALWAYS_EAGER}"
  CELERY_TASK_EAGER_PROPAGATES: "${CELERY_TASK_EAGER_PROPAGATES}"
  
  # Logging
  LOG_LEVEL: "${LOG_LEVEL}"
  DJANGO_LOG_LEVEL: "${DJANGO_LOG_LEVEL}" 