# Dynamic Frontend Service Template
# Usage: envsubst < frontend-service.yaml | kubectl apply -f -

apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_PREFIX}-frontend-service
  namespace: ${PROJECT_PREFIX}-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0.0"
    environment: ${ENVIRONMENT}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: frontend 