apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_PREFIX}-google-calendar-mcp
  namespace: ${PROJECT_PREFIX}-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: google-calendar-mcp
    environment: ${ENVIRONMENT}
spec:
  replicas: ${GOOGLE_CALENDAR_MCP_REPLICAS}
  selector:
    matchLabels:
      app.kubernetes.io/name: ${PROJECT_PREFIX}
      app.kubernetes.io/component: google-calendar-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${PROJECT_PREFIX}
        app.kubernetes.io/component: google-calendar-mcp
        environment: ${ENVIRONMENT}
    spec:
      serviceAccountName: ${PROJECT_PREFIX}-sa
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: google-calendar-mcp
        image: ${ACR_LOGIN_SERVER}/${PROJECT_NAME}-google-calendar-mcp:${IMAGE_TAG}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: ${PROJECT_PREFIX}-google-calendar-mcp-config
        env:
        # No additional MCP env; token passed from agent via header/param
        resources:
          requests:
            memory: ${GOOGLE_CALENDAR_MCP_MEMORY_REQUEST}
            cpu: ${GOOGLE_CALENDAR_MCP_CPU_REQUEST}
          limits:
            memory: ${GOOGLE_CALENDAR_MCP_MEMORY_LIMIT}
            cpu: ${GOOGLE_CALENDAR_MCP_CPU_LIMIT}
        # Health checks disabled - FastMCP doesn't provide health endpoints
        # The server is monitored via application logs and container status
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1