# Simple NGINX Ingress for HotCalls
# This replaces the complex Application Gateway setup

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotcalls-ingress
  namespace: hotcalls-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # API routes go to backend
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hotcalls-backend-internal
            port:
              number: 80
      # Health check
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: hotcalls-backend-internal
            port:
              number: 80
      # Admin routes
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: hotcalls-backend-internal
            port:
              number: 80
      # Static files
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: hotcalls-backend-internal
            port:
              number: 80
      # Frontend (catch-all)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hotcalls-frontend-service
            port:
              number: 80 