# Simple NGINX Ingress for ${PROJECT_PREFIX}
# This routes traffic from external load balancer to internal services
# Frontend serves from root /, API serves from /api/, /admin/, /health/
# 
# TLS Support: When ENABLE_TLS=true and HOST_DOMAIN is set, this ingress will:
# - Configure TLS termination with the provided certificate
# - Redirect HTTP to HTTPS
# - Restrict access to the specified domain

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${PROJECT_PREFIX}-ingress
  namespace: ${PROJECT_PREFIX}-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: ingress
    environment: ${ENVIRONMENT}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # SSL redirect settings - these will be overridden by envsubst based on ENABLE_TLS
    nginx.ingress.kubernetes.io/ssl-redirect: "${ENABLE_TLS:-false}"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "${ENABLE_TLS:-false}"
spec:
  # TLS configuration - only added when ENABLE_TLS=true
  ${ENABLE_TLS:+tls:}
  ${ENABLE_TLS:+- hosts:}
  ${ENABLE_TLS:+    - ${HOST_DOMAIN}}
  ${ENABLE_TLS:+  secretName: ${TLS_SECRET_NAME}}
  rules:
  # Host-based routing when domain is configured
  ${HOST_DOMAIN:+- host: ${HOST_DOMAIN}}
  ${HOST_DOMAIN:+  http:}
  # Default routing without host restriction
  ${HOST_DOMAIN:-}- http:
      paths:
      # API routes (order matters - most specific first)
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ${PROJECT_PREFIX}-backend-internal
            port:
              number: 8000
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: ${PROJECT_PREFIX}-backend-internal
            port:
              number: 8000
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: ${PROJECT_PREFIX}-backend-internal
            port:
              number: 8000
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: ${PROJECT_PREFIX}-backend-internal
            port:
              number: 8000
      # Frontend route (catch-all, must be last)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${PROJECT_PREFIX}-frontend-service
            port:
              number: 80 