# Agent Secrets Template 
# Usage: envsubst < outboundagent-secrets.yaml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
  name: ${PROJECT_PREFIX}-outboundagent-secrets
  namespace: ${PROJECT_PREFIX}-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: outboundagent
    environment: ${ENVIRONMENT}
type: Opaque
data:
  # LiveKit Configuration (Required)
  LIVEKIT_URL: ${LIVEKIT_URL_B64}
  LIVEKIT_API_KEY: ${LIVEKIT_API_KEY_B64}
  LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET_B64}
  
  # AI Model APIs (Required)
  OPENAI_API_KEY: ${OPENAI_API_KEY_B64}
  DEEPGRAM_API_KEY: ${DEEPGRAM_API_KEY_B64}
  ELEVEN_API_KEY: ${ELEVEN_API_KEY_B64}
  
  # MCP Server Configuration (Optional)
  MCP_SERVER_URL: ${MCP_SERVER_URL_B64}
  
  # Additional service keys if needed
  TRUNK_ID: ${TRUNK_ID_B64}
  ELEVEN_VOICE_ID: ${ELEVEN_VOICE_ID_B64}
  
  # PostgreSQL Configuration (Agent uses POSTGRES_* variables)
  POSTGRES_HOST: ${DB_HOST_B64}
  POSTGRES_PORT: ${DB_PORT_B64}
  POSTGRES_DATABASE: ${DB_NAME_B64}
  POSTGRES_USER: ${DB_USER_B64}
  POSTGRES_PASSWORD: ${DB_PASSWORD_B64}
  
  # Agent Configuration
  AGENT_NAME: ${AGENT_NAME_B64}
  NAME: ${NAME_B64}
  SIP_PROVIDER: ${SIP_PROVIDER_B64}
  
  # Call Event Configuration (new endpoint without auth)
  CALL_EVENT_ENDPOINT_URL: ${CALL_EVENT_ENDPOINT_URL_B64}
  CALL_EVENT_TIMEOUT: ${CALL_EVENT_TIMEOUT_B64}
  CALL_EVENT_RETRY_ATTEMPTS: ${CALL_EVENT_RETRY_ATTEMPTS_B64}
  CALL_EVENT_RETRY_BASE_MS: ${CALL_EVENT_RETRY_BASE_MS_B64}
  
  # Legacy Call Log Configuration (kept for compatibility)
  CALL_LOG_ENDPOINT_URL: ${CALL_LOG_ENDPOINT_URL_B64}
  CALL_LOG_TIMEOUT: ${CALL_LOG_TIMEOUT_B64}
  CALL_LOG_MAX_RETRIES: ${CALL_LOG_MAX_RETRIES_B64}