# Agent-Specific ConfigMap Template
# Usage: envsubst < outboundagent-configmap.yaml | kubectl apply -f -

apiVersion: v1
kind: ConfigMap
metadata:
  name: ${PROJECT_PREFIX}-outboundagent-config
  namespace: ${PROJECT_PREFIX}-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: outboundagent
    environment: ${ENVIRONMENT}
data:
  # MCP Configuration
  MCP_TRANSPORT: "${MCP_TRANSPORT}"
  MCP_TIMEOUT: "${MCP_TIMEOUT}"
  MCP_LOG_LEVEL: "${MCP_LOG_LEVEL}"
  MCP_LOG_FORMAT: "${MCP_LOG_FORMAT}"
  MCP_LOG_TOOLS: "${MCP_LOG_TOOLS}"
  MCP_LOG_CONNECTIONS: "${MCP_LOG_CONNECTIONS}"
  
  # Call Duration and Audio Settings
  RING_DURATION: "${RING_DURATION}"
  ENABLE_BACKGROUND_AUDIO: "${ENABLE_BACKGROUND_AUDIO}"
  OFFICE_AMBIENCE_VOLUME: "${OFFICE_AMBIENCE_VOLUME}"
  TYPING_SOUND_VOLUME: "${TYPING_SOUND_VOLUME}"
  
  # Agent Runtime Settings
  ENVIRONMENT: "${ENVIRONMENT}"
  LOG_LEVEL: "${LOG_LEVEL}"
  AGENT_PORT: "8080"
  
  # Service Discovery for Agent
  BACKEND_SERVICE_URL: "http://${PROJECT_PREFIX}-backend-service"
  BACKEND_API_PORT: "80"
  
  # PostgreSQL Configuration (Non-secret)
  POSTGRES_ENABLED: "true"