apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: outboundagent-critical
value: 1000000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Critical priority for outbound agent; must always schedule."


