# Note: This is a template file. In production, secrets should be:
# 1. Retrieved from Azure Key Vault using the CSI driver
# 2. Created via CI/CD pipeline with proper values
# 3. Never committed to git with real values

apiVersion: v1
kind: Secret
metadata:
  name: hotcalls-secrets
  namespace: hotcalls-production
  labels:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Django settings
  SECRET_KEY: "REPLACE_WITH_AZURE_KEY_VAULT_VALUE"
  ALLOWED_HOSTS: "your-production-domain.com,your-apim-gateway.azure-api.net"
  
  # Database credentials
  DB_NAME: "hotcalls"
  DB_USER: "REPLACE_WITH_AZURE_KEY_VAULT_VALUE"
  DB_PASSWORD: "REPLACE_WITH_AZURE_KEY_VAULT_VALUE"
  DB_HOST: "REPLACE_WITH_POSTGRES_FQDN"
  
  # Redis credentials
  REDIS_HOST: "REPLACE_WITH_REDIS_HOST"
  REDIS_PASSWORD: "REPLACE_WITH_REDIS_PASSWORD"
  
  # Celery configuration
  CELERY_BROKER_URL: "redis://:REPLACE_WITH_REDIS_PASSWORD@REPLACE_WITH_REDIS_HOST:6379/0"
  CELERY_RESULT_BACKEND: "redis://:REPLACE_WITH_REDIS_PASSWORD@REPLACE_WITH_REDIS_HOST:6379/0"
  
  # Azure Storage
  AZURE_ACCOUNT_NAME: "REPLACE_WITH_STORAGE_ACCOUNT_NAME"
  AZURE_STORAGE_KEY: "REPLACE_WITH_AZURE_KEY_VAULT_VALUE"
  AZURE_CUSTOM_DOMAIN: "REPLACE_WITH_CDN_ENDPOINT"
  
  # Azure Key Vault
  AZURE_KEY_VAULT_URL: "https://REPLACE_WITH_KEYVAULT_NAME.vault.azure.net/"
  AZURE_CLIENT_ID: "REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID"
  
  # Application Insights
  AZURE_MONITOR_CONNECTION_STRING: "REPLACE_WITH_AZURE_KEY_VAULT_VALUE"
  
  # CORS allowed origins
  CORS_ALLOWED_ORIGINS: "https://your-frontend-domain.com"
  
  # API base URL
  BASE_URL: "https://your-apim-gateway.azure-api.net"

---
apiVersion: v1
kind: Secret
metadata:
  name: hotcalls-secrets
  namespace: hotcalls-staging
  labels:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Django settings
  SECRET_KEY: "staging-secret-key-replace-with-real-value"
  ALLOWED_HOSTS: "staging-domain.com,staging-apim.azure-api.net"
  
  # Database credentials
  DB_NAME: "hotcalls_staging"
  DB_USER: "staging_user"
  DB_PASSWORD: "staging_password"
  DB_HOST: "staging-postgres-server.postgres.database.azure.com"
  
  # Redis credentials
  REDIS_HOST: "staging-redis-host"
  REDIS_PASSWORD: "staging-redis-password"
  
  # Celery configuration
  CELERY_BROKER_URL: "redis://:staging-redis-password@staging-redis-host:6379/0"
  CELERY_RESULT_BACKEND: "redis://:staging-redis-password@staging-redis-host:6379/0"
  
  # Azure Storage
  AZURE_ACCOUNT_NAME: "stagingstorage"
  AZURE_STORAGE_KEY: "staging-storage-key"
  AZURE_CUSTOM_DOMAIN: "staging-cdn-endpoint.azureedge.net"
  
  # Azure Key Vault
  AZURE_KEY_VAULT_URL: "https://staging-keyvault.vault.azure.net/"
  AZURE_CLIENT_ID: "staging-managed-identity-client-id"
  
  # Application Insights
  AZURE_MONITOR_CONNECTION_STRING: "staging-app-insights-connection-string"
  
  # CORS allowed origins
  CORS_ALLOWED_ORIGINS: "https://staging-frontend.com"
  
  # API base URL
  BASE_URL: "https://staging-apim.azure-api.net"

---
apiVersion: v1
kind: Secret
metadata:
  name: hotcalls-secrets
  namespace: hotcalls-development
  labels:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Django settings
  SECRET_KEY: "development-secret-key-for-testing-only"
  ALLOWED_HOSTS: "localhost,127.0.0.1,dev-hotcalls.local"
  
  # Database credentials
  DB_NAME: "hotcalls_dev"
  DB_USER: "dev_user"
  DB_PASSWORD: "dev_password"
  DB_HOST: "dev-postgres-server.postgres.database.azure.com"
  
  # Redis credentials
  REDIS_HOST: "dev-redis-host"
  REDIS_PASSWORD: ""
  
  # Celery configuration
  CELERY_BROKER_URL: "redis://dev-redis-host:6379/0"
  CELERY_RESULT_BACKEND: "redis://dev-redis-host:6379/0"
  
  # Azure Storage
  AZURE_ACCOUNT_NAME: "devstorage"
  AZURE_STORAGE_KEY: "dev-storage-key"
  AZURE_CUSTOM_DOMAIN: ""
  
  # Azure Key Vault
  AZURE_KEY_VAULT_URL: "https://dev-keyvault.vault.azure.net/"
  AZURE_CLIENT_ID: "dev-managed-identity-client-id"
  
  # Application Insights
  AZURE_MONITOR_CONNECTION_STRING: ""
  
  # CORS allowed origins
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
  
  # API base URL
  BASE_URL: "http://localhost:8000" 