# Dynamic Secrets Template
# Usage: envsubst < secrets.yaml | kubectl apply -f -
# NEVER commit real secrets to Git!

apiVersion: v1
kind: Secret
metadata:
  name: hotcalls-secrets
  namespace: hotcalls-${ENVIRONMENT:-dev}
  labels:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: secrets
    environment: ${ENVIRONMENT:-dev}
type: Opaque
stringData:
  # Django core settings
  SECRET_KEY: "${SECRET_KEY:-django-insecure-dev-key-replace-me}"
  ALLOWED_HOSTS: "${ALLOWED_HOSTS:-localhost,127.0.0.1}"
  
  # Database credentials
  DB_NAME: "${DB_NAME:-hotcalls_${ENVIRONMENT:-dev}}"
  DB_USER: "${DB_USER:-hotcalls_user}"
  DB_PASSWORD: "${DB_PASSWORD:-change-me}"
  DB_HOST: "${DB_HOST:-localhost}"
  
  # Redis credentials
  REDIS_HOST: "${REDIS_HOST:-localhost}"
  REDIS_PORT: "${REDIS_PORT:-6379}"
  REDIS_DB: "${REDIS_DB:-0}"
  REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
  
  # Celery configuration
  CELERY_BROKER_URL: "${CELERY_BROKER_URL:-redis://localhost:6379/0}"
  CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND:-redis://localhost:6379/0}"
  
  # Azure Storage credentials
  AZURE_ACCOUNT_NAME: "${AZURE_ACCOUNT_NAME:-devstorage}"
  AZURE_STORAGE_KEY: "${AZURE_STORAGE_KEY:-dev-storage-key}"
  AZURE_CUSTOM_DOMAIN: "${AZURE_CUSTOM_DOMAIN:-}"
  
  # Azure Key Vault
  AZURE_KEY_VAULT_URL: "${AZURE_KEY_VAULT_URL:-}"
  AZURE_CLIENT_ID: "${AZURE_CLIENT_ID:-}"
  
  # Application Insights
  AZURE_MONITOR_CONNECTION_STRING: "${AZURE_MONITOR_CONNECTION_STRING:-}"
  
  # CORS settings
  CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS:-http://localhost:3000}"
  
  # API settings
  BASE_URL: "${BASE_URL:-http://localhost:8000}" 