# Dynamic Secrets Template
# Usage: envsubst < secrets.yaml | kubectl apply -f -
# NEVER commit real secrets to Git!

apiVersion: v1
kind: Secret
metadata:
  name: hotcalls-secrets
  namespace: hotcalls-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: secrets
    environment: ${ENVIRONMENT}
type: Opaque
stringData:
  # Django core settings
  SECRET_KEY: "${SECRET_KEY}"
  ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
  
  # Database credentials
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_HOST: "${DB_HOST}"
  
  # Redis credentials - using K8s service name
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  
  # Celery configuration
  CELERY_BROKER_URL: "redis://:${REDIS_PASSWORD}@redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://:${REDIS_PASSWORD}@redis-service:6379/0"
  
  # Azure Storage credentials
  AZURE_ACCOUNT_NAME: "${AZURE_ACCOUNT_NAME}"
  AZURE_STORAGE_KEY: "${AZURE_STORAGE_KEY}"
  AZURE_CUSTOM_DOMAIN: "${AZURE_CUSTOM_DOMAIN:-}"
  
  # Azure Key Vault
  AZURE_KEY_VAULT_URL: "${AZURE_KEY_VAULT_URL:-}"
  AZURE_CLIENT_ID: "${AZURE_CLIENT_ID:-}"
  
  # Application Insights
  AZURE_MONITOR_CONNECTION_STRING: "${AZURE_MONITOR_CONNECTION_STRING:-}"
  
  # Email configuration
  EMAIL_BACKEND: "${EMAIL_BACKEND}"
  EMAIL_HOST: "${EMAIL_HOST}"
  EMAIL_PORT: "${EMAIL_PORT}"
  EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
  EMAIL_USE_SSL: "${EMAIL_USE_SSL}"
  EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
  EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
  DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
  SERVER_EMAIL: "${SERVER_EMAIL}"
  
  # CORS settings
  CORS_ALLOW_ALL_ORIGINS: "${CORS_ALLOW_ALL_ORIGINS:-True}"
  
  # API settings - will be updated with LoadBalancer IP
  BASE_URL: "${BASE_URL:-http://localhost:8000}" 