# Dynamic Secrets Template
# Usage: envsubst < secrets.yaml | kubectl apply -f -
# Set variables first: PROJECT_PREFIX, ENVIRONMENT, and all secret values

apiVersion: v1
kind: Secret
metadata:
  name: ${PROJECT_PREFIX}-secrets
  namespace: ${PROJECT_PREFIX}-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: secrets
    environment: ${ENVIRONMENT}
type: Opaque
stringData:
  # Django settings
  SECRET_KEY: "${SECRET_KEY}"
  ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
  
  # Database configuration (from Terraform outputs)
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_HOST: "${DB_HOST}"
  
  # Redis configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379/0"
  
  # Celery configuration (constructed from Redis vars)
  CELERY_BROKER_URL: "redis://:${REDIS_PASSWORD}@redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://:${REDIS_PASSWORD}@redis:6379/0"
  
  # Azure Storage & CDN (from Terraform outputs)
  AZURE_ACCOUNT_NAME: "${AZURE_ACCOUNT_NAME}"
  AZURE_STORAGE_KEY: "${AZURE_STORAGE_KEY}"
  AZURE_CUSTOM_DOMAIN: "${AZURE_CUSTOM_DOMAIN}"
  AZURE_CLIENT_ID: "${AZURE_CLIENT_ID:-}"
  AZURE_KEY_VAULT_URL: "${AZURE_KEY_VAULT_URL:-}"
  AZURE_MONITOR_CONNECTION_STRING: "${AZURE_MONITOR_CONNECTION_STRING:-}"
  
  # Email configuration
  EMAIL_BACKEND: "${EMAIL_BACKEND}"
  EMAIL_HOST: "${EMAIL_HOST}"
  EMAIL_PORT: "${EMAIL_PORT}"
  EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
  EMAIL_USE_SSL: "${EMAIL_USE_SSL}"
  EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
  EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
  DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
  SERVER_EMAIL: "${SERVER_EMAIL}"
  
  # Application URLs
  BASE_URL: "${BASE_URL}"
  
  # LiveKit Configuration (if set)
  LIVEKIT_URL: "${LIVEKIT_URL}"
  LIVEKIT_API_KEY: "${LIVEKIT_API_KEY}"
  LIVEKIT_API_SECRET: "${LIVEKIT_API_SECRET}"
  
  # SIP Trunk Configuration (if set)
  TRUNK_ID: "${TRUNK_ID}"
  SIP_PROVIDER: "${SIP_PROVIDER}"
  
  # Stripe Configuration (if set)
  STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
  STRIPE_PUBLISHABLE_KEY: "${STRIPE_PUBLISHABLE_KEY}"
  STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
  
  # Meta (Facebook/Instagram) Integration
  META_APP_ID: "${META_APP_ID}"
  META_APP_SECRET: "${META_APP_SECRET}"
  META_REDIRECT_URI: "${META_REDIRECT_URI}"
  META_API_VERSION: "${META_API_VERSION}"
  
  # LiveKit Agent Configuration
  LIVEKIT_AGENT_NAME: "${LIVEKIT_AGENT_NAME}"
  
  # Note: Agent count and concurrency are now managed via database (LiveKitAgent model) 