apiVersion: v1
kind: Service
metadata:
  name: hotcalls-backend-service
  namespace: hotcalls-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: backend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: backend

---
apiVersion: v1
kind: Service
metadata:
  name: hotcalls-backend-internal
  namespace: hotcalls-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: backend-internal
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app.kubernetes.io/name: hotcalls
    app.kubernetes.io/component: backend 