apiVersion: batch/v1
kind: Job
metadata:
  name: ${PROJECT_PREFIX}-setup-plans
  namespace: ${PROJECT_PREFIX}-${ENVIRONMENT}
  labels:
    app.kubernetes.io/name: ${PROJECT_PREFIX}
    app.kubernetes.io/component: backend-task
    app.kubernetes.io/version: "1.0.0"
    environment: ${ENVIRONMENT}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${PROJECT_PREFIX}
        app.kubernetes.io/component: backend-task
        app.kubernetes.io/version: "1.0.0"
    spec:
      serviceAccountName: ${PROJECT_PREFIX}-sa
      restartPolicy: Never
      containers:
      - name: backend
        image: ${ACR_LOGIN_SERVER}/${PROJECT_PREFIX}-backend:${IMAGE_TAG}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: ${PROJECT_PREFIX}-config
        - secretRef:
            name: ${PROJECT_PREFIX}-secrets
        command: ["sh", "-c"]
        # Set SETUP_FORCE_FLAG to "--force" via envsubst if you want a destructive reset
        args: ["python manage.py setup_plans ${SETUP_FORCE_FLAG}"]

